### ISSUE TITLE
request.user.userId not defined when authenticated using API token

### ISSUE THREAD

**Issue by nedgar** [shahednasser/medusa-marketplace#10]
In `LoggedInUserMiddleware.consume`, if you log `req.user`, using e.g. `console.log("[LoggedInUserMiddleware.consume] req.user:", req.user);`, it shows like the following when logged in using the normal JWT stored in session cookie:

```
[LoggedInUserMiddleware.consume] req.user: {
  userId: 'usr_01GA78EP49XQFQP7D2NM5739Q3',
  iat: 1660259966,
  exp: 1660346366
}
```

But if you clear cookies on the client and auth using an API token instead, it shows like:
```
[LoggedInUserMiddleware.consume] req.user: User {
  id: 'usr_01GA79QJK38M8N4XBP4SE7G0Z4',
  created_at: 2022-08-11T20:32:30.812Z,
  updated_at: 2022-08-11T20:33:05.057Z,
  deleted_at: null,
  role: 'member',
  email: 'openharbor@medusa-test.com',
  first_name: 'Service',
  last_name: 'Account',
  api_token: 't0p-s3cr3t',
  metadata: null,
  store_id: null,
  role_id: null
}
```

I'm not sure why the shape of `req.user` differs, but it means `req.user.userId` is undefined, and the call to `userService.retrieve(...)` fails with:
```
UnhandledPromiseRejectionWarning: Error: Failed to validate id: undefined
    at UserService.BaseService.validateId_ (.../my-store/node_modules/medusa-interfaces/dist/base-service.js:193:19)
    at UserService.retrieve (.../my-store/node_modules/medusa-marketplace/dist/modules/user/user.service.js:26:34)
    at consume (.../my-store/node_modules/medusa-marketplace/dist/modules/user/loggedInUser.middleware.js:15:48)
    at Layer.handle [as handle_request] (.../my-store/node_modules/express/lib/router/layer.js:95:5)
    at next (.../my-store/node_modules/express/lib/router/route.js:137:13)
```

A workaround is to replace `LoggedInUserMiddleware.consume` with one that does:
```js
  userService.retrieve(req.user.userId || req.user.id, ...)
```
 instead of:
```js
  userService.retrieve(req.user.userId, ...)
```

**Comment by nedgar** [comment]
Alternatively:
```ts
...
    const userId = req.user?.userId ?? req.user?.id;
    if (!userId) {
      throw new MedusaError(MedusaError.Types.UNEXPECTED_STATE, "Unable to determine user ID");
    }

    const loggedInUser = await userService.retrieve(userId, { select: ["id", "store_id"] });
...
```

**Comment by nedgar** [comment]
FYI @adrien2p

**Comment by nedgar** [comment]
Also, when a request fails like this, no response is sent due to an unresolved promise. Instead, the client hangs indefinitely waiting for a response. I suspect some error handling middleware gets lost in the -extender or -marketplace overrides.

**Comment by nedgar** [comment]
From `medusa-extender`'s core types:

```ts
/**
 * Describe the expected request from a middleware {@link MedusaMiddleware}.
 */
export declare type MedusaAuthenticatedRequest = Request & MedusaRequest & {
    user?: {
        id?: string;
        userId: string;
    };
    userId: string;
    session: {
        jwt: string;
    };
};
```

This suggests that an authenticated request should already have the `req.userId` and `req.user.userId` populated (though `user` is optional, not sure why). However `req.userId` is not populated in the call to `LoggedInUserMiddleware.consume`, and `req.user.userId` is not populated when authenticating using an API token. So this suggests a deeper issue with `medusa-extender`. If it worked as it seems to suggest, then perhaps `medusa-marketplace`'s `LoggedInUserMiddleware` wouldn't be needed.

**Comment by adrien2p** [comment]
Hey there, first of all. The type `MedusaAuthenticatedRequest ` is just an helper but you can use what ever you want instead.

About the fact that the user object differ, it is just due to the fact that in the first case you get the data from the decoded jwt and in the other case the data from the user fetched on which the token has been found.

About hanging requests, using an express server, when an error is thrown in an handler, it must be pass to the `next` function. Otherwise nothing happen. But this is just the way Express work and it is not related to medusa nor the extender. This is the reason behind the `wrapHandler` used by medusa which basically wrap an handler and catch any error to pass it to the next function.

About the fact that the user props is optional, this is only a reflection of the core, which internally looks for user.userId or user that's it. Ut is mostly a legacy support for older versions.

And finally, the loggedInUser middleware is there to get the authenticated user and register it as part of the container for the subsequent usage in the scoped services.

Hope that answers your questions 👍

**Comment by nedgar** [comment]
@adrien2p thanks for clarifying, and so promptly :). 

> About the fact that the user object differ, it is just due to the fact that in the first case you get the data from the decoded jwt and in the other case the data from the user fetched on which the token has been found.

It would be good to normalize that in the core, to match `MedusaAuthenticatedRequest` or similar.

> In your case you can just do .catch(next)

I'll modify the `LoggedInUserMiddleware` to do that.

> This package is just a tutorial that aims to guide you through the usage of the extender and mostly teach you how to use it.

and 

> Another important point is that the tutorial is not necessarily updated to follow newer versions

I understand, but I hope we can improve consistency in the core and/or -extender so that -marketplace's extensions like `LoggedInUserMiddleware`, which aren't really marketplace specific, can be made available to all.

> And finally, the loggedInUser middleware is there to get the authenticated user and register it as part of the container for the subsequent usage in the scoped services and be able to always have a real user entity.  ...

Exactly -- this argues for it being part of the core support.

I will continue to explore -extender and -marketplace, and am happy to contribute patches / pull requests back as appropriate.
