### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeORMError: Entity metadata for User#teamRole was not found. Check if you specified a correct entity object and if it's connected in the connection options.     at new TypeORMError (/home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/typeorm/error/TypeORMError.js:9:28)

### ISSUE THREAD

**Issue by jtqfaire** [shahednasser/medusa-marketplace#11]
Hi,

I'am trying to use this plugin but it doesn't works and i have the following error:

```
npm run start

> medusa-starter-default@0.0.1 start /home/kereval.com/bcu/perso/lrvlb/lrvlb
> npm run build && NODE_ENV=development node ./dist/main.js


> medusa-starter-default@0.0.1 build /home/kereval.com/bcu/perso/lrvlb/lrvlb
> rm -rf dist && ./node_modules/.bin/tsc -p tsconfig.json

[Server]      - 8/24/2022, 5:06:05 PM   [ValidatorsLoader] Loading custom validators into the underlying @medusajs
[Server]      - 8/24/2022, 5:06:05 PM   [ValidatorsLoader] 0 validators applied
[Server]      - 8/24/2022, 5:06:05 PM   [EntitiesLoader] Loading overridden entities into the underlying @medusajs
[Server]      - 8/24/2022, 5:06:05 PM   [EntitiesLoader] Entity overridden - User
[Server]      - 8/24/2022, 5:06:05 PM   [EntitiesLoader] Entity overridden - Product
[Server]      - 8/24/2022, 5:06:05 PM   [EntitiesLoader] Entity overridden - Store
[Server]      - 8/24/2022, 5:06:05 PM   [EntitiesLoader] Entity overridden - Order
[Server]      - 8/24/2022, 5:06:05 PM   [EntitiesLoader] 4 entities overridden
[Server]      - 8/24/2022, 5:06:05 PM   [RepositoriesLoader] Loading overridden entities into the underlying @medusajs
[Server]      - 8/24/2022, 5:06:05 PM   [RepositoriesLoader] Repository overridden - UserRepository
[Server]      - 8/24/2022, 5:06:05 PM   [RepositoriesLoader] Repository overridden - ProductRepository
[Server]      - 8/24/2022, 5:06:05 PM   [RepositoriesLoader] Repository overridden - StoreRepository
[Server]      - 8/24/2022, 5:06:05 PM   [RepositoriesLoader] Repository overridden - OrderRepository
[Server]      - 8/24/2022, 5:06:05 PM   [RepositoriesLoader] 4 repositories overridden
[Server]      - 8/24/2022, 5:06:05 PM   [ServicesLoader] Loading services into the underlying @medusajs
[Server]      - 8/24/2022, 5:06:05 PM   [SubscribersLoader] Loading custom subscribers into the underlying @medusajs
[Server]      - 8/24/2022, 5:06:05 PM   [SubscribersLoader] 1 subscribers built
✔ Models initialized – 43ms
✔ Plugin models initialized – 1ms
✔ Repositories initialized – 47ms
⠋ Initializing database[Server]      - 8/24/2022, 5:06:05 PM   [EntitiesLoader] Loading custom entities into the underlying @medusajs
[Server]      - 8/24/2022, 5:06:05 PM   [EntitiesLoader] 0 entities registered
[Server]      - 8/24/2022, 5:06:05 PM   [RepositoriesLoader] Loading custom entities into the underlying @medusajs
[Server]      - 8/24/2022, 5:06:05 PM   [RepositoriesLoader] 0 repositories registered
(node:469738) UnhandledPromiseRejectionWarning: TypeORMError: Entity metadata for User#teamRole was not found. Check if you specified a correct entity object and if it's connected in the connection options.
    at new TypeORMError (/home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/typeorm/error/TypeORMError.js:9:28)
    at /home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:603:23
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.computeInverseProperties (/home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:599:34)
    at /home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:85:74
    at Array.forEach (<anonymous>)
    at EntityMetadataBuilder.build (/home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/typeorm/metadata-builder/EntityMetadataBuilder.js:85:25)
    at ConnectionMetadataBuilder.<anonymous> (/home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/typeorm/connection/ConnectionMetadataBuilder.js:86:160)
    at step (/home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/tslib/tslib.js:144:27)
    at Object.next (/home/kereval.com/bcu/perso/lrvlb/lrvlb/node_modules/tslib/tslib.js:125:57)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:469738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:469738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠇ Initializing database
```

It keep blocking on " Initializing database"

Any idea how what's happen ?

My src/main.ts:

```
import express = require('express');
const config = require('../medusa-config');
import { Medusa } from 'medusa-extender';
import { resolve } from 'path';
import { ExampleModule } from './modules/example/example.module';
import { ProductModule, UserModule, StoreModule, OrderModule } from 'medusa-marketplace';

async function bootstrap() {
    const expressInstance = express();
    
    await new Medusa(resolve(__dirname, '..'), expressInstance).load([
  UserModule,
  ProductModule,
  StoreModule,
  OrderModule
]);
    
    const port = config?.serverConfig?.port ?? 9000;
    expressInstance.listen(port, () => {
        console.info('Server successfully started on port ' + port);
    });
}

bootstrap();

```
Thx for your help

**Comment by manojvirat457** [comment]
Getting same error,

```

F:\Medusa\Portal\SkryptStore\backend\node_modules\medusa-marketplace\dist\modules\user\user.service.js:26
        const validatedId = this.validateId_(userId);
                                 ^

TypeError: this.validateId_ is not a function
    at UserService.retrieve (F:\Medusa\Portal\SkryptStore\backend\node_modules\medusa-marketplace\dist\modules\user\user.service.js:26:34)        
    at consume (F:\Medusa\Portal\SkryptStore\backend\node_modules\medusa-marketplace\dist\modules\user\loggedInUser.middleware.js:14:48)
    at Layer.handle [as handle_request] (F:\Medusa\Portal\SkryptStore\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (F:\Medusa\Portal\SkryptStore\backend\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (F:\Medusa\Portal\SkryptStore\backend\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (F:\Medusa\Portal\SkryptStore\backend\node_modules\express\lib\router\layer.js:95:5)
    at F:\Medusa\Portal\SkryptStore\backend\node_modules\express\lib\router\index.js:284:15
    at param (F:\Medusa\Portal\SkryptStore\backend\node_modules\express\lib\router\index.js:365:14)
    at param (F:\Medusa\Portal\SkryptStore\backend\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (F:\Medusa\Portal\SkryptStore\backend\node_modules\express\lib\router\index.js:421:3)
```
`main.ts`
```
import express = require('express');
const config = require('../medusa-config');
import { Medusa } from 'medusa-extender';
import { resolve } from 'path';
import { ProductModule, UserModule, StoreModule, OrderModule, InviteModule, RoleModule, PermissionModule } from 'medusa-marketplace';

async function bootstrap() {
    const expressInstance = express();

    await new Medusa(resolve(__dirname, '..'), expressInstance).load(
        [
            UserModule,
            ProductModule,
            StoreModule,
            OrderModule,
            InviteModule,
            RoleModule,
            PermissionModule
        ]
    );

    const port = config?.serverConfig?.port ?? 9000;
    expressInstance.listen(port, () => {
        console.info('Server successfully started on port ' + port);
    });
}

bootstrap();
```

**Comment by adrien2p** [comment]
This.validateId_ is now an util and must be imported separatly

**Comment by matiasf** [comment]
Hi @adrien2p, same issue here, I try to found this util on marketplace-plugin, medusa-extender and medusa core but couldn't find it to try to fix this issue. Do you know where this util is to fix this problem?

**Comment by adrien2p** [comment]
It is in medusa/dist/utils/validateId if it is not already exported by the utils/index

**Comment by matiasf** [comment]
I'm trying to overwrite de created services by marketplace-plugin with extender to change this behavior to use the util for validateId and buildQuery, which was another failing method. Now all my class looks good but have trouble to override the service and gives me the next error:
```
medusa-server-default | 
medusa-server-default | src/modules/user/user.service.ts(33,5): error TS2416: Property 'withTransaction' in type 'UserService' is not assignable to the same property in base type 'UserService'.
medusa-server-default |   Type '(transactionManager: EntityManager) => UserService' is not assignable to type '(transactionManager?: EntityManager) => this'.
medusa-server-default |     Type 'UserService' is not assignable to type 'this'.
medusa-server-default |       'UserService' is assignable to the constraint of type 'this', but 'this' could be instantiated with a different subtype of constraint 'UserService'.
```

My current class is this:
```js
import { EntityManager } from "typeorm";
import EventBusService from "@medusajs/medusa/dist/services/event-bus";
import { FindConfig } from "@medusajs/medusa/dist/types/common";
import Utils from "@medusajs/medusa/dist/utils";
import { MedusaError } from "medusa-core-utils";
import MedusaMarketplaceUserService from "medusa-marketplace/dist/modules/user/user.service";
import { Service } from "medusa-extender";
import { User } from "medusa-marketplace/dist/modules/user/user.entity";
import UserRepository from "medusa-marketplace/dist/modules/user/user.repository";

type ConstructorParams = {
    manager: EntityManager;
    userRepository: typeof UserRepository;
    eventBusService: EventBusService;
    loggedInUser?: User;
};

@Service({ override: MedusaMarketplaceUserService })
export default class UserService extends MedusaMarketplaceUserService {
    private readonly manager: EntityManager;
    private readonly userRepository: typeof UserRepository;
    private readonly eventBus: EventBusService;

    constructor(private readonly container: ConstructorParams) {
        super(container);
        this.manager = container.manager;
        this.userRepository = container.userRepository;
        this.eventBus = container.eventBusService;
        this.container = container;
    }

    withTransaction(transactionManager: EntityManager): UserService {
        if (!transactionManager) {
            return this;
        }

        const cloned = new UserService({
            ...this.container,
            manager: transactionManager,
        });

        cloned.transactionManager_ = transactionManager;

        return cloned;
    }

    public async retrieve(
        userId: string,
        config?: FindConfig<User>
    ): Promise<User> {
        const userRepo = this.manager.getCustomRepository(this.userRepository);
        const validatedId = Utils.validateId(userId);
        const query = Utils.buildQuery({ id: validatedId }, config);

        const user = await userRepo.findOne(query);

        if (!user) {
            throw new MedusaError(
                MedusaError.Types.NOT_FOUND,
                `User with id: ${userId} was not found`
            );
        }

        return user as User;
    }

    public async addUserToStore(user_id, store_id) {
        await this.atomicPhase_(async (m) => {
            const userRepo = m.getCustomRepository(this.userRepository);
            const query = Utils.buildQuery({ id: user_id });

            const user = await userRepo.findOne(query);
            if (user) {
                user.store_id = store_id;
                await userRepo.save(user);
            }
        });
    }
}
```
I'm newbie with Typescript, but is this a good approach to fix the issue with extender?

**Comment by ahsanwtc** [comment]
getting the same error
