### ISSUE TITLE
Startup migrations don't work properly

### ISSUE THREAD

**Issue by matiasf** [shahednasser/medusa-marketplace#13]
I have created a setup of the marketplace with medusa-extender medusa core. My current develop.sh script on a docker startup is this:
```sh
echo "Running custom development script, starting medusa migrations"
#Run migrations to ensure the database is updated
medusa migrations run

echo "Running medusa extender migrations"
#Run migrations on Medusa Extender modules
medex m --run

echo "Starting development environment"
#Start development environment
npm run start
```

And this is the execution result of this script:
```
medusa-server-default | info:    Migrations completed.
medusa-server-default | Running medusa extender migrations
medusa-server-default | 42 migrations are already loaded in the database.
medusa-server-default | 7 migrations were found in the source code.
medusa-server-default | swapFulfillmentStatusRequiresAction1661863940645 is the last executed migration. It was executed on Tue Aug 30 2022 12:52:20 GMT+0000 (Coordinated Universal Time).
medusa-server-default | 7 migrations are new migrations that needs to be executed.
medusa-server-default | Migration addStoreIdToUser1611063162649 has been executed successfully.
medusa-server-default | Migration addStoreIdToProduct1645034402086 has been executed successfully.
medusa-server-default | Migration OrderMigration1652101349791 has been executed successfully.
medusa-server-default | Migration InviteMigration1655123458263 has been executed successfully.
medusa-server-default | Migration "RoleMigration1655131148363" failed, error: target.split is not a function
medusa-server-default | /usr/local/lib/node_modules/medusa-extender/node_modules/typeorm/driver/postgres/PostgresDriver.js:753
medusa-server-default |         var parts = target.split(".");
medusa-server-default |                            ^
medusa-server-default |
medusa-server-default | TypeError: target.split is not a function
medusa-server-default |     at PostgresDriver.parseTableName (/usr/local/lib/node_modules/medusa-extender/node_modules/typeorm/driver/postgres/PostgresDriver.js:753:28)
medusa-server-default |     at PostgresQueryRunner.BaseQueryRunner.getTablePath (/usr/local/lib/node_modules/medusa-extender/node_modules/typeorm/query-runner/BaseQueryRunner.js:373:45)
medusa-server-default |     at PostgresQueryRunner.<anonymous> (/usr/local/lib/node_modules/medusa-extender/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:2071:129)
medusa-server-default |     at step (/usr/local/lib/node_modules/medusa-extender/node_modules/tslib/tslib.js:144:27)
medusa-server-default |     at Object.next (/usr/local/lib/node_modules/medusa-extender/node_modules/tslib/tslib.js:125:57)
medusa-server-default |     at fulfilled (/usr/local/lib/node_modules/medusa-extender/node_modules/tslib/tslib.js:115:62)
medusa-server-default |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
medusa-server-default |
medusa-server-default | Node.js v17.1.0
medusa-server-default | Starting development environment
```

After trying a couple of things I could determine the problematic migrations are the user migrations, the role migrations and the permission migrations. I have been trying to fix it individually because all are creating migrations but without success.

Another strange behavior is if I import one by one the problematic migrations after correctly executing the correct ones it works ok, and for this reason I couldn't determine yet if it is a bug of the migrations or something else.

Any clue on this is very helpful, let you know if found a fix for it.

**Comment by matiasf** [comment]
Well, after changing the perspective problem while write this post I change the develop.sh for this and works ok:

```sh
echo "Running custom development script, starting medusa migrations"
#Run migrations to ensure the database is updated
medusa migrations run

echo "Running medusa extender migrations"
#Run migrations on Medusa Extender modules
./node_modules/.bin/medex m --run

echo "Starting development environment"
#Start development environment
npm run start
```
